// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ_RzygnucF1GU-mNoK2-2iBSR99vBrss',
    appId: '1:1035889022713:web:f8c8461178c08be3223428',
    messagingSenderId: '1035889022713',
    projectId: 'todo-93f93',
    authDomain: 'todo-93f93.firebaseapp.com',
    storageBucket: 'todo-93f93.firebasestorage.app',
    measurementId: 'G-YMWEZJ5NS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr2RmkYD5mmkiAOUMvoc6R7lrvLgn59lg',
    appId: '1:1035889022713:android:da0f92f344f01b5c223428',
    messagingSenderId: '1035889022713',
    projectId: 'todo-93f93',
    storageBucket: 'todo-93f93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFIQqbdel4BfFrdV4l1_GGJkwgL1aPqnI',
    appId: '1:1035889022713:ios:90a530b477fa884e223428',
    messagingSenderId: '1035889022713',
    projectId: 'todo-93f93',
    storageBucket: 'todo-93f93.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFIQqbdel4BfFrdV4l1_GGJkwgL1aPqnI',
    appId: '1:1035889022713:ios:90a530b477fa884e223428',
    messagingSenderId: '1035889022713',
    projectId: 'todo-93f93',
    storageBucket: 'todo-93f93.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ_RzygnucF1GU-mNoK2-2iBSR99vBrss',
    appId: '1:1035889022713:web:1ca6c96e8b359d11223428',
    messagingSenderId: '1035889022713',
    projectId: 'todo-93f93',
    authDomain: 'todo-93f93.firebaseapp.com',
    storageBucket: 'todo-93f93.firebasestorage.app',
    measurementId: 'G-5MJQXXKEVT',
  );
}
